apiVersion: apps/v1
kind: Deployment
metadata:
  name: zarvis-docs-deployment
  labels:
    app: zarvis-ar-app
spec:
  selector:
    matchLabels:
      app: zarvis-ar-app
  replicas: 1
  template:
    metadata:
      labels:
        app: zarvis-ar-app
    spec:
      containers:
      - name: zarvis-ar
        image: byxiaopeng/openshift-aria2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 3
---
kind: Service
apiVersion: v1
metadata:
  name: docs
spec:
  ports:
  - name: http
    port: 8080
  selector:
    app: zarvis-ar-app
